disabled_rules:
  - todo
  - trailing_comma
  - identifier_name # Disabled because of backtick test names and simple variable names like 'pr'
  - large_tuple # Tuple with 3 elements is often fine
  - function_body_length # Allow longer functions for now (e.g. tests)
  - file_length
  - type_body_length
  - nesting
  - cyclomatic_complexity
  - force_unwrapping # Allow force unwrapping for now (useful in tests and previews)

opt_in_rules:
  - empty_count
  - empty_string
  # - force_unwrapping # Disabled above

line_length: 120

excluded:
  - "**/DerivedData"
  - "**/.build"
  - "**/build"
  - "**/GitReviewItApp/.build"
