PN := "PNPM"
PNR := PN + " run"

# Default recipe - shows available commands
default:
    @just --list --unsorted

# Publish to GitHub Pages
publish: prepare
    {{ PNR }} publish

# Bootstrap web (ensure pnpm and install modules)
bootstrap: install-pnpm prepare

# Prepare web dependencies (install modules)
prepare: install-modules

[private]
install-pnpm:
    corepack enable
    corepack prepare pnpm@latest --activate

[private]
install-modules:
    {{ PN }} install
